name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  flutter_build:
    name: Build Flutter Web App for Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web App
        run: flutter build web

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: |
            build/web
            firebase.json
            .firebaserc

  make_api_doc_preview:
    name: Generate API documentation
    runs-on: ubuntu-latest
    needs: flutter_build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate API documentation
        run: dart doc --output doc/api

      - name: Firebase deploy API documentation
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TERA_FOOD }}
          projectId: tera-food
          target: tera-food-doc

  release_firebase_preview:
    name: Deploy Flutter Web app (Preview)
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    needs: flutter_build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build

      - name: Firebase deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TERA_FOOD }}
          projectId: tera-food
          target: tera-food